---
name: golang

on:
  - push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup go
        id: go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.5'

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v1

      - name: Set GOPATH
        # FIXME: gopath environment variable not set
        # See https://github.com/actions/setup-go/issues/12
        # See https://github.com/actions/setup-go/issues/14
        run: |
          echo "::set-env name=GOPATH::$(dirname $GITHUB_WORKSPACE)"
          echo "::add-path::$(dirname $GITHUB_WORKSPACE)/bin"
